// <auto-generated />
namespace Jabbot.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204240040561_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so+9kk0nVjqXhR+lxWWSExOu8PH9PjHYeAqOPbF/U2ylh1V6/uV7l3ONnH327atp89npVV9O3eeu3pda/V34dfEAfvayrVV6316/y8yiEs9lH6d0Qyt0uGAtkEAIQ/Oyjs2V7b++j9MW6LLNJSR+cZ2WTf5SuPn30uq3q/PN8mdcZvfoya9u8plk7m+U8QCXUo9Wnt6PVw7s7e6DV3Wy5rNqsJRboDaODNP41iL5ua+Kmj9Jnxbt89jxfXrRzi+wX2TvzCf36UfrVsiDmo5faep1HBre517PmdInmlkZPqqrMs+UNgB7fdRO/kR1e522LoXwNPtBXvw4DeK/+aOYHev3JrFx/s93K351eX2SXxQWToTtHRkWkr/KSGzTzYiV6aawT+Pu7Rs/qavGqQjfd737/19W6nmIo1UCDN1l9ARi34eDjpqmmBeMTMpPDJRzg6XKW3oSY0NgbGFF1XbbFqiymhMNnH32rR7cNYM1wPLAdrduBvjMe73ZH742zL8BkXdqsIJFQEogFeZq1Gb7J3/VpgLcI0agCJpvjaD2AcG/0IUClQQySpWgHhDfAHhyPr7xmQ7zXVVW3mHGLv496iODt5tgD1CNqVyuGI47wup1W5y3cFXfBuBV3B/yKx19kqxVG4d7UT9LX4mScbL9+f29iITDuTpuIU2GxtT2Rps4u8s631DVh+qyoG2bQSQaddTJb9JrdmolNf3Fe7k+iYUjzHn735UY9ry7PdwA5kj6jUS7I+vCAdbgRDugDSOH9ZWVW3+gPnVTlerG8nb+1CbKYLh+afHJ7CJ4D4oPxPu7Deny3Q6nunHi6XVt2RKU717fiBCvJX58FjLJ6/7kffHOIsPpCd7a9j28/SR8+zept+CD0ox/+9IZ6MjrHnoG4YSq9lrecMqj9+Fz11H+fNF9Dvi3QmwUdlLO4fQ201fzdEu3359CN+JFWnxXst501cEqtA/u1iNE1p31O6lnVbhPLx8aImr+tVVWLFphaplY3hO+ZOGnyUUrEuCxmMG+vr2lAizEajF//ovKkLEhyXIMvsmVxnjftm+ptjnQEWeCvnwqwQU7TzMr/7+YDChDoxvjvPeMq0YzSwfIyq6fzrN5aZO/uvDekXmw+Kdr/n8Xl/y+fgSBGHgQVjXu7Ix/WOx4lNsH8WQhYu0HYBwSUAVzDXD5A+1kIqR/4EqPlNWY+K0mzNm1NurXnAbykdMW0WGVlfCR9A/T+agUUt910v3mar/Il+LMz4tt0fGsTBAxsRx1Ju4lK7xng90Oo7txuCvBvEd+Lvfrso9mkIrYQHr8poO12almo15v9JtaNftmH/3UyBO+bIYgT6nUkmrtFeiCWV/jZSQP0HRNiufXSrkCQADTFhQMB52uZTwNms23OlueVEYMORqZJR1t+kbfZjDjxuG6L82za0tfTvGl4uKyTP/vodDHJZ2fLL9ftat3SkPPFpLz2iQHZ2dQ/5zpCnB9/ueI85DcxBEKzoCHkXy6frItyZvF+FjHaAyAglGoWMZctzOPFtYX0olreEpCS76nRJW/yxYpSrnnz5fJ1dpkP43YzDUOKPX5aZBd1tvApKJ8YEc6oZ68L6sB/w/VHfxK70vLX0f8TAAD//1tzd6hzGwAA"; }
        }
    }
}
